name: Build, test and deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Create Database
        run: touch ./database/database.sqlite

      - name: Copy .env
        run: cp .env.test .env

      - name: Install app
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Install Node-js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM packages
        run: npm install

      - name: Build NPM assets
        run: npm run build

      - name: Run migrations
        run: php artisan migrate

      - name: Test PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Test PHPUnit
        run: ./vendor/bin/phpunit

      # - name: Synchoronize Files To Server
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SOURCE: "."
      #     REMOTE_HOST: ${{ secrets.VPS_HOST }}
      #     REMOTE_USER: ${{ secrets.VPS_USER }}
      #     TARGET: "/var/www/html/{project_file}"

      # - name: Run Remote/Artisan Commands
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.VPS_HOST }}
      #     username: ${{ secrets.VPS_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /var/www/html/{project_file}
      #       php artisan migrate --force
      #       php artisan optimize
